export enum TestEnum {
  CLICK = "click",
  CHARS_33 = "this is a upper bound test char33",
  CHARS_48 = "This is a string value of 48 characters for test",
  CHARS_3 = "ch3",
  CHARS_2 = "c2",
  DIV = "DIV",
  SECTION = "SECTION",
  ARTICLE = "ARTICLE",
  BUTTON = "BUTTON",
  INPUT = "INPUT",
  LI = "LI",
  TEST_ID = "test-id-123",
  TEST_NAME = "I am test ToDo",
  LABEL = "LABEL",
}
